source 'http://rubygems.org'

gem 'rails', '5.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'social_engine', :path => File.expand_path("../../", __FILE__)

group :test do
  gem 'cucumber'
  gem 'cucumber-rails', '>= 0.4.0'
  gem 'capybara', '>= 0.4.1.2'
  gem 'database_cleaner'
  gem 'launchy'
  gem "autotest-rails"
  gem "autotest-notification"
  gem "rspec"
  gem "rspec-rails", ">= 2.8.0"
  gem "spork"
  gem "launchy"
  gem "systemu"
end

