source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'social_engine', :path => File.expand_path("../../", __FILE__)

group :test do
  gem 'cucumber', '>= 4.0.0'
  gem 'cucumber-rails', '>= 0.4.0'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem "autotest-rails"
  gem "autotest-notification"
  gem "rspec"
  gem "rspec-rails"
  gem "spork"
  gem "launchy"
  gem "systemu"
end

